### ISSUE TITLE
Download problem with Symantec EndPoint Protection

### ISSUE THREAD

**Issue by AKA-MMM** [3MFConsortium/lib3mf-binaries#4]
Hi,
I just tried to download the binaries to test them and is them in a VC++ project. My company uses Symantec EndPoint Protection Small Business Edition. This antivirus reject the file lib3mf_win64.dll with the reason WS_Reputation.1 (see https://community.norton.com/en/forums/clarification-wsreputation1-detection)

B.R.

**Comment by martinweismann** [comment]
Hi @AKA-MMM ,
does this still occur when you download the lib3mf_sdk.zip: https://github.com/3MFConsortium/lib3mf-binaries/blob/master/lib3mf_sdk.zip?
If so, can you provide a screenshot? I would go through the whitelisting process that Symantec provides on their page.
Cheers

**Comment by AKA-MMM** [comment]
Hi,
I confirm that, when I try to unzip the file Symantec still remove it. Below the screen shoot with Symantec details.
[cid:image001.png@01D433BE.DB463040]

De : Martin Weismann <notifications@github.com>
Envoyé : mardi 14 août 2018 10:52
À : 3MFConsortium/lib3mf-binaries <lib3mf-binaries@noreply.github.com>
Cc : Alain Kaufmann <alain.kaufmann@minmaxmedical.com>; Mention <mention@noreply.github.com>
Objet : Re: [3MFConsortium/lib3mf-binaries] Download problem with Symantec EndPoint Protection (#4)


Hi @AKA-MMM<https://github.com/AKA-MMM> ,
does this still occur when you download the lib3mf_sdk.zip: https://github.com/3MFConsortium/lib3mf-binaries/blob/master/lib3mf_sdk.zip?
If so, can you provide a screenshot? I would go through the whitelisting process that Symantec provides on their page.
Cheers

**Comment by martinweismann** [comment]
@AKA-MMM : thanks for the confirmation. I contacted Symantec about the false positive.
I'll keep you posted once there is an update. Cheers!

**Comment by martinweismann** [comment]
Hi @AKA-MMM ,
the semi-automatic whitelisting of Symantec accepted lib3MF.dll.
However, I suspect that Symantec only accepted the very specific binary that I uploaded to them. Could you update your Anti-Virus and try another download?

In any case: A good way to improve lib3MF.dll's standing with Anti-Virus software is to digitally sign it (which is generally a good idea). I'll try to get a code signing certificate for lib3MF's binaries for the future.

**Comment by AKA-MMM** [comment]
Hi,
I updated the Symantec definitions. But I still have the same problem. For a full update of Symantec I have not the user rights.

De : Martin Weismann <notifications@github.com>
Envoyé : jeudi 16 août 2018 08:53
À : 3MFConsortium/lib3mf-binaries <lib3mf-binaries@noreply.github.com>
Cc : Alain Kaufmann <alain.kaufmann@minmaxmedical.com>; Mention <mention@noreply.github.com>
Objet : Re: [3MFConsortium/lib3mf-binaries] Download problem with Symantec EndPoint Protection (#4)


Hi @AKA-MMM<https://github.com/AKA-MMM> ,
the semi-automatic whitelisting of Symantec accepted lib3MF.dll.
However, I suspect that Symantec only accepted the very specific binary that I uploaded to them. Could you update your Anti-Virus and try another download?

In any case: A good way to improve lib3MF.dll's standing with Anti-Virus software is to digitally sign it (which is generally a good idea). I'll try to get a code signing certificate for lib3MF's binaries for the future.

**Comment by martinweismann** [comment]
Hi @AKA-MMM ,

i took a while, but finally, windows binaries of lib3mf are digitally signed! This should resolve most issues with anti-virus software.

![image](https://user-images.githubusercontent.com/30837766/60014925-76873c80-9682-11e9-9946-40690b8aaaed.png)


Get the beta version of lib3mf v2 from:
- https://github.com/3MFConsortium/lib3mf/releases/tag/v2.0.0-beta or 
- https://github.com/3MFConsortium/lib3mf-binaries/tree/lib3mf_v2_beta
